fn main() {
    // App commands are ACL-gated: the webview loads the site from a remote
    // origin, and Tauri refuses remote-origin access to custom commands unless
    // a capability lists them. `commands` autogenerates `allow-<command>`
    // permissions (under src-tauri/permissions/autogenerated) which
    // capabilities/default.json then grants. Without this, every
    // `window.__TAURI__.core.invoke(...)` from the site was rejected.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "get_autostart",
                "set_autostart",
                "get_start_minimized",
                "set_start_minimized",
                "set_unread_count",
                "get_running_games",
                "get_current_game",
                "get_watch_state",
                "open_external",
            ]),
        ),
    )
    .expect("failed to run tauri-build");
}
