// In-call overlay (desktop app): static pins for the wiring across the Rust
// shell, the overlay page, and the site. The Tauri app itself is built by CI
// (app-release.yml), so this pins everything that has to line up for the
// release build to work: commands registered in all three places (lib.rs,
// build.rs, capabilities), the overlay page contract, and the site's hooks.
'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const appRoot = path.join(root, 'app');
let pass = 0, fail = 0;
function ok(cond, name) {
  if (cond) { pass++; }
  else { fail++; console.error('FAIL:', name); }
}
function read(p) { return fs.readFileSync(p, 'utf8'); }
function has(p, s) { return read(p).includes(s); }

const lib = path.join(appRoot, 'src-tauri/src/lib.rs');
const libSrc = read(lib);

// --- Rust commands exist and are registered ---
for (const cmd of ['get_overlay_settings', 'set_overlay_settings', 'overlay_state', 'overlay_update', 'overlay_fit']) {
  ok(libSrc.includes('fn ' + cmd + '('), 'lib.rs defines ' + cmd);
  ok(has(path.join(appRoot, 'src-tauri/build.rs'), '"' + cmd + '"'), 'build.rs lists ' + cmd);
  ok(fs.existsSync(path.join(appRoot, 'src-tauri/permissions/autogenerated', cmd + '.toml')),
    'permission TOML exists for ' + cmd);
  const toml = read(path.join(appRoot, 'src-tauri/permissions/autogenerated', cmd + '.toml'));
  ok(toml.includes('commands.allow = ["' + cmd + '"]'), 'TOML allows ' + cmd);
}
const caps = JSON.parse(read(path.join(appRoot, 'src-tauri/capabilities/default.json')));
for (const cmd of ['get_overlay_settings', 'set_overlay_settings', 'overlay_state', 'overlay_update', 'overlay_fit']) {
  const id = 'allow-' + cmd.replace(/_/g, '-');
  ok(caps.permissions.includes(id), 'capabilities grant ' + id);
}
ok(caps.windows.includes('overlay'), 'capabilities cover the overlay window');

// --- overlay window construction ---
ok(libSrc.includes('WebviewWindowBuilder::new'), 'overlay window builder used');
ok(libSrc.includes('"overlay"'), 'overlay window labeled "overlay"');
ok(libSrc.includes('WebviewUrl::App("overlay.html".into())'), 'overlay loads bundled overlay.html');
ok(libSrc.includes('.transparent(true)'), 'overlay window transparent');
ok(libSrc.includes('.decorations(false)'), 'overlay window borderless');
ok(libSrc.includes('.always_on_top(true)'), 'overlay window always-on-top');
ok(libSrc.includes('.skip_taskbar(true)'), 'overlay window skips taskbar');
ok(libSrc.includes('set_ignore_cursor_events(true)'), 'overlay window click-through');
ok(libSrc.includes('win.emit("overlay-speakers"'), 'shell emits overlay-speakers event');
ok(libSrc.includes('fn overlay_fit('), 'overlay_fit sizes the window to the visible rows');
ok(libSrc.includes('fn overlay_place('), 'overlay_place anchors the window in its corner');
ok(!libSrc.includes('speakers.len().clamp'), 'window no longer sized by total speaker count');
for (const corner of ['top-left', 'top-right', 'bottom-left', 'bottom-right']) {
  ok(libSrc.includes('"' + corner + '"'), 'corner arm: ' + corner);
}
ok(libSrc.includes('overlay: Mutex::new(OverlayState::default())'), 'State carries overlay snapshot');
ok(libSrc.includes('overlay_settings: Mutex::new(OverlaySettings::default())'), 'State caches overlay settings');
ok(libSrc.includes('load_settings(&app).overlay'), 'setup primes overlay settings cache');
// --- overlay only appears while gaming ---
ok(libSrc.includes('only_while_gaming'), 'OverlaySettings has only_while_gaming');
ok(libSrc.includes('default_overlay_only_while_gaming'), 'only_while_gaming has a serde default');
ok(/fn default_overlay_only_while_gaming\(\)[^{]*\{[^}]*true/s.test(libSrc), 'only_while_gaming defaults to true');
ok(/settings\.only_while_gaming\s*&&\s*!gaming/.test(libSrc), 'apply_overlay hides the panel when no game is running');
ok(/current_game\.lock\(\)\.unwrap\(\)\.is_some\(\)/.test(libSrc), 'apply_overlay reads game detection state');
ok(libSrc.includes('*state.current_game.lock().unwrap() = game.clone();\n                                update_tray(&app, game.as_deref());\n                                // Game started or stopped: re-evaluate the\n                                // "only while gaming" overlay gate.\n                                apply_overlay(&app);'),
  'game watcher re-evaluates the overlay on game change');

// --- overlay page contract ---
const page = path.join(appRoot, 'dist/overlay.html');
ok(fs.existsSync(page), 'app/dist/overlay.html exists');
const pageSrc = read(page);
ok(pageSrc.includes("listen('overlay-speakers'"), 'page listens for overlay-speakers');
ok(pageSrc.includes("invoke('overlay_state')"), 'page pulls overlay_state on load');
ok(pageSrc.includes("invoke('overlay_fit'"), 'page reports visible rows through overlay_fit');
ok(pageSrc.includes('background: transparent'), 'page background transparent');
ok(/if\s*\(!s\s*\|\|\s*!s\.speaking\)\s*continue/.test(pageSrc), 'page renders only speaking participants');
ok(pageSrc.includes("classList.add('in')"), 'page fades rows in');
ok(pageSrc.includes("classList.remove('in')"), 'page fades rows out when speaking stops');
ok(pageSrc.includes('fadeTimer'), 'page cancels a fade-out if the speaker talks again');

// --- site: voice.js pushes snapshots ---
const voice = read(path.join(root, 'public/js/voice.js'));
ok(voice.includes('function overlaySnapshot()'), 'voice.js defines overlaySnapshot');
ok(voice.includes('function syncOverlayNow()'), 'voice.js defines syncOverlayNow');
ok(voice.includes('function scheduleOverlaySync()'), 'voice.js defines scheduleOverlaySync');
ok(voice.includes("inv('overlay_update'"), 'voice.js invokes overlay_update');
ok(voice.includes('isDesktopShell()'), 'voice.js gates on desktop shell');
ok(/setSpeakingUI\(userId, speaking\) \{[^}]*scheduleOverlaySync\(\)/s.test(voice),
  'setSpeakingUI schedules an overlay sync');
ok(voice.includes('syncOverlayNow(); // hides the in-call overlay at once'),
  'leaveVoice hides the overlay immediately');

// --- site: socket.js remote speaking flips ---
const socket = read(path.join(root, 'public/js/socket.js'));
ok((socket.match(/scheduleOverlaySync\(\)/g) || []).length >= 2,
  'socket.js voice-state (dm + server) schedules overlay sync');

// --- site: settings tab ---
const index = read(path.join(root, 'public/index.html'));
ok(index.includes('data-tab="overlay"'), 'settings has an Overlay tab button');
ok(index.includes('id="set-overlay"'), 'settings has an overlay pane');
const settings = read(path.join(root, 'public/js/settings.js'));
ok(settings.includes('function renderOverlayTab()'), 'settings.js defines renderOverlayTab');
ok(settings.includes("if (t === 'overlay') tabSpinWhile(pane, renderOverlayTab());"),
  'setSettingsTab renders the overlay tab');
ok(settings.includes("inv('get_overlay_settings')"), 'tab reads get_overlay_settings');
ok(settings.includes("inv('set_overlay_settings'"), 'tab writes set_overlay_settings');
ok(settings.includes('ov-switch'), 'tab uses a toggle switch for enable');
ok(settings.includes('ov-corner'), 'tab uses a visual corner picker');
ok(!/renderOverlayTab[\s\S]*?createElement\('select'\)/.test(settings.slice(settings.indexOf('async function renderOverlayTab()'), settings.indexOf('// ---------- games tab'))),
  'tab no longer uses a corner dropdown');
ok(settings.includes("'Only while gaming'"), 'tab has an only-while-gaming row');
ok(settings.includes('only_while_gaming: gInp.checked'), 'tab saves the gaming-only preference');
ok(settings.includes('cur.only_while_gaming !== false'), 'gaming-only defaults on for old settings');

// --- styles for the revamped tab ---
const css = read(path.join(root, 'public/styles.css'));
ok(css.includes('.ov-switch'), 'styles define the overlay toggle switch');
ok(css.includes('.ov-corners'), 'styles define the corner picker grid');
ok(css.includes('.ov-corner[aria-pressed="true"]'), 'styles mark the selected corner');

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
