// In-call overlay (desktop app): static pins for the wiring across the Rust
// shell, the overlay page, and the site. The Tauri app itself is built by CI
// (app-release.yml), so this pins everything that has to line up for the
// release build to work: commands registered in all three places (lib.rs,
// build.rs, capabilities), the overlay page contract, and the site's hooks.
'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const appRoot = path.join(root, 'app');
let pass = 0, fail = 0;
function ok(cond, name) {
  if (cond) { pass++; }
  else { fail++; console.error('FAIL:', name); }
}
function read(p) { return fs.readFileSync(p, 'utf8'); }
function has(p, s) { return read(p).includes(s); }

const lib = path.join(appRoot, 'src-tauri/src/lib.rs');
const libSrc = read(lib);

// --- Rust commands exist and are registered ---
for (const cmd of ['get_overlay_settings', 'set_overlay_settings', 'overlay_state', 'overlay_update']) {
  ok(libSrc.includes('fn ' + cmd + '('), 'lib.rs defines ' + cmd);
  ok(has(path.join(appRoot, 'src-tauri/build.rs'), '"' + cmd + '"'), 'build.rs lists ' + cmd);
  ok(fs.existsSync(path.join(appRoot, 'src-tauri/permissions/autogenerated', cmd + '.toml')),
    'permission TOML exists for ' + cmd);
  const toml = read(path.join(appRoot, 'src-tauri/permissions/autogenerated', cmd + '.toml'));
  ok(toml.includes('commands.allow = ["' + cmd + '"]'), 'TOML allows ' + cmd);
}
const caps = JSON.parse(read(path.join(appRoot, 'src-tauri/capabilities/default.json')));
for (const cmd of ['get_overlay_settings', 'set_overlay_settings', 'overlay_state', 'overlay_update']) {
  const id = 'allow-' + cmd.replace(/_/g, '-');
  ok(caps.permissions.includes(id), 'capabilities grant ' + id);
}
ok(caps.windows.includes('overlay'), 'capabilities cover the overlay window');

// --- overlay window construction ---
ok(libSrc.includes('WebviewWindowBuilder::new'), 'overlay window builder used');
ok(libSrc.includes('"overlay"'), 'overlay window labeled "overlay"');
ok(libSrc.includes('WebviewUrl::App("overlay.html".into())'), 'overlay loads bundled overlay.html');
ok(libSrc.includes('.transparent(true)'), 'overlay window transparent');
ok(libSrc.includes('.decorations(false)'), 'overlay window borderless');
ok(libSrc.includes('.always_on_top(true)'), 'overlay window always-on-top');
ok(libSrc.includes('.skip_taskbar(true)'), 'overlay window skips taskbar');
ok(libSrc.includes('set_ignore_cursor_events(true)'), 'overlay window click-through');
ok(libSrc.includes('win.emit("overlay-speakers"'), 'shell emits overlay-speakers event');
for (const corner of ['top-left', 'top-right', 'bottom-left', 'bottom-right']) {
  ok(libSrc.includes('"' + corner + '"'), 'corner arm: ' + corner);
}
ok(libSrc.includes('overlay: Mutex::new(OverlayState::default())'), 'State carries overlay snapshot');
ok(libSrc.includes('overlay_settings: Mutex::new(OverlaySettings::default())'), 'State caches overlay settings');
ok(libSrc.includes('load_settings(&app).overlay'), 'setup primes overlay settings cache');

// --- overlay page contract ---
const page = path.join(appRoot, 'dist/overlay.html');
ok(fs.existsSync(page), 'app/dist/overlay.html exists');
const pageSrc = read(page);
ok(pageSrc.includes("listen('overlay-speakers'"), 'page listens for overlay-speakers');
ok(pageSrc.includes("invoke('overlay_state')"), 'page pulls overlay_state on load');
ok(pageSrc.includes('background: transparent'), 'page background transparent');
ok(pageSrc.includes('.talking'), 'page styles talking state');

// --- site: voice.js pushes snapshots ---
const voice = read(path.join(root, 'public/js/voice.js'));
ok(voice.includes('function overlaySnapshot()'), 'voice.js defines overlaySnapshot');
ok(voice.includes('function syncOverlayNow()'), 'voice.js defines syncOverlayNow');
ok(voice.includes('function scheduleOverlaySync()'), 'voice.js defines scheduleOverlaySync');
ok(voice.includes("inv('overlay_update'"), 'voice.js invokes overlay_update');
ok(voice.includes('isDesktopShell()'), 'voice.js gates on desktop shell');
ok(/setSpeakingUI\(userId, speaking\) \{[^}]*scheduleOverlaySync\(\)/s.test(voice),
  'setSpeakingUI schedules an overlay sync');
ok(voice.includes('syncOverlayNow(); // hides the in-call overlay at once'),
  'leaveVoice hides the overlay immediately');

// --- site: socket.js remote speaking flips ---
const socket = read(path.join(root, 'public/js/socket.js'));
ok((socket.match(/scheduleOverlaySync\(\)/g) || []).length >= 2,
  'socket.js voice-state (dm + server) schedules overlay sync');

// --- site: settings tab ---
const index = read(path.join(root, 'public/index.html'));
ok(index.includes('data-tab="overlay"'), 'settings has an Overlay tab button');
ok(index.includes('id="set-overlay"'), 'settings has an overlay pane');
const settings = read(path.join(root, 'public/js/settings.js'));
ok(settings.includes('function renderOverlayTab()'), 'settings.js defines renderOverlayTab');
ok(settings.includes("if (t === 'overlay') tabSpinWhile(pane, renderOverlayTab());"),
  'setSettingsTab renders the overlay tab');
ok(settings.includes("inv('get_overlay_settings')"), 'tab reads get_overlay_settings');
ok(settings.includes("inv('set_overlay_settings'"), 'tab writes set_overlay_settings');

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
