// In-call overlay (desktop app): static pins for the wiring across the Rust
// shell, the overlay page, and the site. The Tauri app itself is built by CI
// (app-release.yml), so this pins everything that has to line up for the
// release build to work: commands registered in all three places (lib.rs,
// build.rs, capabilities), the overlay page contract, and the site's hooks.
'use strict';
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const appRoot = path.join(root, 'app');
let pass = 0, fail = 0;
function ok(cond, name) {
  if (cond) { pass++; }
  else { fail++; console.error('FAIL:', name); }
}
function read(p) { return fs.readFileSync(p, 'utf8'); }
function has(p, s) { return read(p).includes(s); }

const lib = path.join(appRoot, 'src-tauri/src/lib.rs');
const libSrc = read(lib);

// --- Rust commands exist and are registered ---
for (const cmd of ['get_overlay_settings', 'set_overlay_settings', 'overlay_state', 'overlay_update', 'overlay_message', 'overlay_fit']) {
  ok(libSrc.includes('fn ' + cmd + '('), 'lib.rs defines ' + cmd);
  ok(has(path.join(appRoot, 'src-tauri/build.rs'), '"' + cmd + '"'), 'build.rs lists ' + cmd);
  ok(fs.existsSync(path.join(appRoot, 'src-tauri/permissions/autogenerated', cmd + '.toml')),
    'permission TOML exists for ' + cmd);
  const toml = read(path.join(appRoot, 'src-tauri/permissions/autogenerated', cmd + '.toml'));
  ok(toml.includes('commands.allow = ["' + cmd + '"]'), 'TOML allows ' + cmd);
}
const caps = JSON.parse(read(path.join(appRoot, 'src-tauri/capabilities/default.json')));
for (const cmd of ['get_overlay_settings', 'set_overlay_settings', 'overlay_state', 'overlay_update', 'overlay_message', 'overlay_fit']) {
  const id = 'allow-' + cmd.replace(/_/g, '-');
  ok(caps.permissions.includes(id), 'capabilities grant ' + id);
}
ok(caps.windows.includes('overlay'), 'capabilities cover the overlay window');

// --- overlay window construction ---
ok(libSrc.includes('WebviewWindowBuilder::new'), 'overlay window builder used');
ok(libSrc.includes('"overlay"'), 'overlay window labeled "overlay"');
ok(libSrc.includes('WebviewUrl::App("overlay.html".into())'), 'overlay loads bundled overlay.html');
ok(libSrc.includes('.transparent(true)'), 'overlay window transparent');
ok(libSrc.includes('.decorations(false)'), 'overlay window borderless');
ok(libSrc.includes('.always_on_top(true)'), 'overlay window always-on-top');
ok(libSrc.includes('.skip_taskbar(true)'), 'overlay window skips taskbar');
ok(libSrc.includes('set_ignore_cursor_events(true)'), 'overlay window click-through');
ok(libSrc.includes('win.emit("overlay-speakers"'), 'shell emits overlay-speakers event');
ok(libSrc.includes('fn overlay_fit('), 'overlay_fit sizes the window to the visible rows');
ok(libSrc.includes('fn overlay_place('), 'overlay_place anchors the window in its corner');
ok(!libSrc.includes('speakers.len().clamp'), 'window no longer sized by total speaker count');
for (const corner of ['top-left', 'top-right', 'bottom-left', 'bottom-right']) {
  ok(libSrc.includes('"' + corner + '"'), 'corner arm: ' + corner);
}
ok(libSrc.includes('overlay: Mutex::new(OverlayState::default())'), 'State carries overlay snapshot');
ok(libSrc.includes('overlay_settings: Mutex::new(OverlaySettings::default())'), 'State caches overlay settings');
ok(libSrc.includes('load_settings(&app).overlay'), 'setup primes overlay settings cache');
// --- the overlay is always gaming-gated: no toggle, no message about it ---
ok(!libSrc.includes('only_while_gaming'), 'OverlaySettings has no only_while_gaming field');
ok(/settings\.enabled && in_call && gaming && focused/.test(libSrc),
  'the gate always requires a running (and focused, on Windows) game');
ok(/if !overlay_gate_open\(app\) \{\s*if let Some\(w\) = app\.get_webview_window\("overlay"\)/.test(libSrc),
  'apply_overlay hides the panel whenever the gate is closed');
ok(/current_game\.lock\(\)\.unwrap\(\)\.is_some\(\)/.test(libSrc), 'apply_overlay reads game detection state');
// --- overlay only over the game window (Windows foreground tracking) ---
ok(libSrc.includes('game_pids: Mutex<std::collections::HashSet<sysinfo::Pid>>'), 'State tracks game PIDs');
ok(libSrc.includes('game_focused: AtomicBool'), 'State tracks game window focus');
ok(libSrc.includes('fn GetForegroundWindow()'), 'Windows foreground window FFI declared');
ok(libSrc.includes('fn GetWindowThreadProcessId('), 'Windows foreground PID FFI declared');
ok(libSrc.includes('fn foreground_is_game('), 'foreground_is_game helper exists');
ok(libSrc.includes('pid == own_pid'), 'own windows never flip the focus gate');
ok(libSrc.includes('sysinfo::Pid::from_u32(pid)'), 'foreground PID compared against game PIDs');
ok(libSrc.includes('let focus_app = app.clone();'), 'focus tracker thread spawned in setup');
ok(libSrc.includes('Duration::from_secs(1)'), 'focus tracker polls every second');
ok(/focused != prev/.test(libSrc), 'overlay re-evaluated only when focus changes');
ok(libSrc.includes('pids.insert(p.pid())'), 'watcher collects PIDs evidencing the game');
ok(libSrc.includes('*state.current_game.lock().unwrap() = game.clone();\n                                update_tray(&app, game.as_deref());\n                                // Game started or stopped: re-evaluate the\n                                // "only while gaming" overlay gate.\n                                apply_overlay(&app);'),
  'game watcher re-evaluates the overlay on game change');

// --- overlay page contract ---
const page = path.join(appRoot, 'dist/overlay.html');
ok(fs.existsSync(page), 'app/dist/overlay.html exists');
const pageSrc = read(page);
ok(pageSrc.includes("listen('overlay-speakers'"), 'page listens for overlay-speakers');
ok(pageSrc.includes("invoke('overlay_state')"), 'page pulls overlay_state on load');
ok(pageSrc.includes("invoke('overlay_fit'"), 'page reports visible rows through overlay_fit');
ok(pageSrc.includes('background: transparent'), 'page background transparent');
ok(/if\s*\(!s\s*\|\|\s*!s\.speaking\)\s*continue/.test(pageSrc), 'page renders only speaking participants');
ok(pageSrc.includes("classList.add('in')"), 'page fades rows in');
ok(pageSrc.includes("classList.remove('in')"), 'page fades rows out when speaking stops');
ok(pageSrc.includes('fadeTimer'), 'page cancels a fade-out if the speaker talks again');
// --- rows fade in place: opacity only, no slide or scale while fading ---
function cssRule(src, sel) {
  const m = src.match(new RegExp(sel.replace(/\./g, '\\.') + '\\s*\\{([^}]*)\\}'));
  return m ? m[1] : null;
}
const spRest = cssRule(pageSrc, '.sp');
ok(spRest && !/transform\s*:/.test(spRest), 'resting row has no transform (fades in place)');
ok(spRest && /transition\s*:/.test(spRest) && !/transition\s*:[^;]*transform/.test(spRest),
  'row transition is opacity-only');
const spIn = cssRule(pageSrc, '.sp.in');
ok(spIn && /opacity\s*:\s*1/.test(spIn) && !/transform\s*:/.test(spIn),
  '.sp.in sets opacity only, no transform');
// --- rows float bar-less over the game: no pill, name stays readable ---
ok(spRest && !/background\s*:/.test(spRest), 'row has no background pill');
ok(spRest && !/border-radius/.test(spRest), 'row has no pill rounding');
ok(spRest && !/backdrop-filter/.test(spRest), 'row has no backdrop blur');
const nmRule = cssRule(pageSrc, '.nm');
ok(nmRule && /text-shadow/.test(nmRule), 'name keeps a text shadow for legibility over the game');
// --- panel sits a little below the top edge ---
ok(libSrc.includes('m + drop'), 'top corners nudge the panel down from the edge');
ok(!/bottom-(left|right)"\s*=>\s*\([^)]*\+\s*drop/.test(libSrc), 'bottom corners keep the plain edge margin');

// --- site: voice.js pushes snapshots ---
const voice = read(path.join(root, 'public/js/voice.js'));
ok(voice.includes('function overlaySnapshot()'), 'voice.js defines overlaySnapshot');
ok(voice.includes('function syncOverlayNow()'), 'voice.js defines syncOverlayNow');
ok(voice.includes('function scheduleOverlaySync()'), 'voice.js defines scheduleOverlaySync');
ok(voice.includes("inv('overlay_update'"), 'voice.js invokes overlay_update');
ok(voice.includes('isDesktopShell()'), 'voice.js gates on desktop shell');
ok(/setSpeakingUI\(userId, speaking\) \{[^}]*scheduleOverlaySync\(\)/s.test(voice),
  'setSpeakingUI schedules an overlay sync');
ok(voice.includes('syncOverlayNow(); // hides the in-call overlay at once'),
  'leaveVoice hides the overlay immediately');

// --- site: socket.js remote speaking flips ---
const socket = read(path.join(root, 'public/js/socket.js'));
ok((socket.match(/scheduleOverlaySync\(\)/g) || []).length >= 2,
  'socket.js voice-state (dm + server) schedules overlay sync');

// --- site: settings tab ---
const index = read(path.join(root, 'public/index.html'));
ok(index.includes('data-tab="overlay"'), 'settings has an Overlay tab button');
ok(index.includes('id="set-overlay"'), 'settings has an overlay pane');
const settings = read(path.join(root, 'public/js/settings.js'));
ok(settings.includes('function renderOverlayTab()'), 'settings.js defines renderOverlayTab');
ok(settings.includes("if (t === 'overlay') tabSpinWhile(pane, renderOverlayTab());"),
  'setSettingsTab renders the overlay tab');
ok(settings.includes("inv('get_overlay_settings')"), 'tab reads get_overlay_settings');
ok(settings.includes("inv('set_overlay_settings'"), 'tab writes set_overlay_settings');
ok(settings.includes('ov-switch'), 'tab uses a toggle switch for enable');
ok(settings.includes('ov-corner'), 'tab uses a visual corner picker');
ok(!/renderOverlayTab[\s\S]*?createElement\('select'\)/.test(settings.slice(settings.indexOf('async function renderOverlayTab()'), settings.indexOf('// ---------- games tab'))),
  'tab no longer uses a corner dropdown');
ok(!settings.includes("'Only while gaming'"), 'tab has no only-while-gaming row');
ok(!settings.includes('only_while_gaming'), 'tab never reads or writes the gaming toggle');

// --- message toasts: Rust ---
ok(libSrc.includes('struct OverlayMessage'), 'lib.rs defines OverlayMessage');
const omBody = libSrc.slice(libSrc.indexOf('struct OverlayMessage'), libSrc.indexOf('struct OverlayMessage') + 800);
for (const f of ['name: String', 'avatar_url: Option<String>', 'avatar_color: String', 'source: String', 'text: String']) {
  ok(omBody.includes(f), 'OverlayMessage carries ' + f);
}
ok(libSrc.includes('fn overlay_message('), 'lib.rs defines the overlay_message command');
ok(/overlay_message[\s\S]{0,400}overlay_gate_open/.test(libSrc),
  'overlay_message reuses the panel gate (no toast where the panel would not be)');
ok(libSrc.includes('!state.overlay_settings.lock().unwrap().show_messages'),
  'overlay_message honors the show_messages toggle');
ok(libSrc.includes('win.emit("overlay-message"'), 'shell emits overlay-message event');
ok(libSrc.includes('fn overlay_gate_open('), 'overlay_gate_open helper exists');
ok(/fn apply_overlay[\s\S]{0,600}overlay_gate_open\(app\)/.test(libSrc),
  'apply_overlay uses the shared gate helper');
ok(/async fn overlay_fit\(app: AppHandle, height: f64\)/.test(libSrc),
  'overlay_fit takes a pixel height');
// --- message previews setting ---
ok(/show_messages:\s*bool/.test(libSrc), 'OverlaySettings has a show_messages field');
ok(/fn default_show_messages\(\) -> bool \{\s*true/.test(libSrc), 'show_messages defaults on');
ok(/impl Default for OverlaySettings[\s\S]{0,200}show_messages: default_show_messages\(\)/.test(libSrc),
  'Default impl sets show_messages');
ok(/async fn set_overlay_settings\([\s\S]{0,200}show_messages:\s*bool/.test(libSrc),
  'set_overlay_settings takes show_messages');
// --- message toasts: overlay page ---
ok(pageSrc.includes("listen('overlay-message'"), 'page listens for overlay-message');
ok(pageSrc.includes('id="msgs"'), 'page has a message toast container');
ok(pageSrc.includes("invoke('overlay_fit', { height:"), 'page reports scrollHeight through overlay_fit');
const msgRule = cssRule(pageSrc, '.msg');
ok(msgRule && /border\s*:/.test(msgRule), 'toast card has a border');
ok(msgRule && /border-radius/.test(msgRule), 'toast card is rounded');
ok(msgRule && /background\s*:/.test(msgRule), 'toast card has a dark background');
ok(cssRule(pageSrc, '.msg .src') !== null, 'toast styles the source label');
ok(cssRule(pageSrc, '.msg .tx') !== null, 'toast styles the message preview');
ok(cssRule(pageSrc, '.msg .av') !== null, 'toast styles the avatar');
ok(pageSrc.includes('MSG_MS'), 'toasts auto-expire');
ok(pageSrc.includes('MAX_MSGS'), 'toast stack is capped');
ok(pageSrc.includes('insertBefore(el, msgsBox)'), 'speaker rows stay above the message toasts');
// --- message toasts: site pushes ---
ok(socket.includes('function overlayMessage('), 'socket.js defines overlayMessage');
ok(/case 'message-new': \{\s*const msg = m\.message;\s*if \(msg\) overlayMessage\(msg\);/.test(socket),
  'channel messages are pushed to the overlay');
ok(/case 'dm-new': \{\s*const msg = m\.message;\s*if \(msg\) overlayMessage\(msg\);/.test(socket),
  'DM messages are pushed to the overlay');
ok(socket.includes("inv('overlay_message'") || socket.includes("invoke('overlay_message'"),
  'overlayMessage invokes the overlay_message command');
ok(/function overlayMessage[\s\S]{0,1200}m\.viewOnce \? 'Sent a view-once'/.test(socket),
  'view-once captions never reach the overlay');
ok(/function overlayMessage[\s\S]{0,1200}status === 'dnd'/.test(socket),
  'DND suppresses overlay toasts');
ok(/function overlayMessage[\s\S]{0,1200}isDesktopShell\(\)/.test(socket),
  'overlayMessage gates on the desktop shell');
// --- message toasts: settings tab ---
ok(settings.includes('Show message previews'), 'tab has a message previews row');
ok(settings.includes('showMessages'), 'tab writes showMessages through set_overlay_settings');
ok(settings.includes("cur.show_messages !== false"), 'message previews default on (incl. older builds)');
ok(settings.includes("'show_messages' in cur"), 'tab omits showMessages for builds that lack it');

// --- styles for the revamped tab ---
const css = read(path.join(root, 'public/styles.css'));
ok(css.includes('.ov-switch'), 'styles define the overlay toggle switch');
ok(css.includes('.ov-corners'), 'styles define the corner picker grid');
ok(css.includes('.ov-corner[aria-pressed="true"]'), 'styles mark the selected corner');

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
